language: node_js
node_js:
  - "10"
cache:
  npm: true
  # Cache Cypress binaries
  directories:
    - ~/.cache
addons:
  apt:
    packages:
      # Required for Cypress
      - libgconf-2-4
jobs:
  include:
        - stage: unit-test
          script: npm test
        - stage: integration-test
          script:
            - npm run cypress
            - echo "Yay"
script:
  - npm test
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/static
  on:
    branch: master
