language: node_js
script:
  - npm test
  - npm run build
node_js:
  - "10"
cache:
  directories:
    - "node_modules"
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/static
  on:
    branch: master
