language: node_js
node_js:
  - "10"
cache:
  npm: true
  # Cache Cypress binaries
  directories:
    - ~/.cache
addons:
  apt:
    packages:
      # Required for Cypress
      - libgconf-2-4
jobs:
  include:
    - stage: unit-test
      script:
        - npm run lint
        - npm run unit-test
        - npm run build
    - stage: integration-test
      script:
        # - npm run cypress
        - npm run build
        - npx http-server dist/static --silent &
        - npm run cypress
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/static
  on:
    branch: master
